- name: Ensure pip3 is installed on OL8
  dnf:
    name: python3-pip
    state: present
  become: yes  # Requires root privileges to install system packages

- name: Upgrade pip3 to the latest version
  shell: python3 -m pip install --upgrade pip
  become: yes  # Run with elevated privileges

- name: Install required Python libraries using pip3
  pip:
    name:
      - boto3
      - botocore
    state: present
    executable: pip3

- name: ensure restore directory exists
  file:
    path: "{{ restore_directory }}"
    state: directory

- name: Download Neo4j dump file from S3
  #amazon.aws.s3_object:
  amazon.aws.aws_s3:
    bucket: "{{s3_bucket_name}}"
    object: "/{{s3_folder_name}}/{{dump_file_name}}"
    dest: "/{{restore_directory }}/{{restore_file}}"
    mode: get
  register: download_result

- name: show download status
  debug:
    msg: "{{download_result}}"