---
# tasks file for neo4j-dump

- name: ensure that remote workspace exists
  file:
    path: "{{ remote_workspace }}-{{ tier }}"
    state: directory

- name: verify file is present
  stat:
     path: "{{ remote_workspace }}-{{ tier }}/{{ dump_file_name }}.dump"
  register: file_status


- name: upload dump file to s3
  command: aws s3 cp {{ remote_workspace }}-{{ tier }}/{{ dump_file_name }}.dump s3://{{ s3_bucket_name }}/{{ s3_folder_name }}/{{ dump_file_name }}-{{ timestamp }}.dump
  register: output

- name: show upload status
  debug:
    msg: "{{output.stdout_lines}}"
