Notes: Jenkins pipeline
project: icdc
services:
  backend:
    version: 14.8.0.77
    image: 14.8.0.77
    buildNumber: '77'
  frontend:
    version: Bento-4.0.82
    image: Bento-4.0.82
    buildNumber: '82'
  files:
    version: 1.4.0.59
    image: 1.4.0.59
    buildNumber: '59'
  interoperation:
    version: 1.0.0.75
    image: 1.0.0.75
    buildNumber: '75'
