Notes: Jenkins pipeline
project: icdc
services:
  backend:
    version: 14.8.1.157
    image: 14.8.1.157
    buildNumber: '157'
  frontend:
    version: Bento-4.0.237
    image: Bento-4.0.237
    buildNumber: '237'
  files:
    version: 2.3.1.78
    image: 2.3.1.78
    buildNumber: '78'
  interoperation:
    version: 1.0.0.111
    image: 1.0.0.111
    buildNumber: '111'
  data-retriever:
    version: main.4
    image: main.4
    buildNumber: '4'
