Notes: Jenkins pipeline
project: icdc
services:
  backend:
    version: 14.8.0.78
    image: 14.8.0.78
    buildNumber: '78'
  frontend:
    version: v4.0.0.83
    image: v4.0.0.83
    buildNumber: '83'
  files:
    version: 1.4.0.59
    image: 1.4.0.59
    buildNumber: '59'
  interoperation:
    version: 1.0.0.75
    image: 1.0.0.75
    buildNumber: '75'
