Notes: Jenkins pipeline
project: icdc
services:
  backend:
    version: 14.8.0.80
    image: 14.8.0.80
    buildNumber: '80'
  frontend:
    version: v3.59.8.102
    image: v3.59.8.102
    buildNumber: '102'
  files:
    version: 1.4.0.59
    image: 1.4.0.59
    buildNumber: '59'
  interoperation:
    version: 1.0.0.83
    image: 1.0.0.83
    buildNumber: '83'
  'null':
    version: v4.0.0.114
    image: v4.0.0.114
    buildNumber: '114'
