Notes: Jenkins pipeline
project: icdc
services:
  backend:
    version: 14.8.1.149
    image: 14.8.1.149
    buildNumber: '149'
  frontend:
    version: Bento-4.0.233
    image: Bento-4.0.233
    buildNumber: '233'
  files:
    version: 2.3.1.78
    image: 2.3.1.78
    buildNumber: '78'
  interoperation:
    version: api-outage-revamp.98
    image: api-outage-revamp.98
    buildNumber: '98'
