- name: build files microservice
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    #install collections
    - name: install aws collection
      shell: "ansible-galaxy collection install {{ item | quote }} --force"
      loop:
        - community.docker:<=3.4.3
        - amazon.aws:<=5.4.0
        - community.aws:<=3.2.0
        #- git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,main
        - git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,icdc

#    #docker login
#    - name: docker login
#      include_role:
#        name: bento.common.ecr_login
#      vars:
#        region: us-east-1

    - name: log into ncidockerhub
      community.docker.docker_login:
        username: "{{ lookup('amazon.aws.aws_secret', 'cbiit/docker.username', nested=true, region='us-east-1') }}"
        password: "{{ lookup('amazon.aws.aws_secret', 'cbiit/docker.password', nested=true, region='us-east-1') }}"
        registry: https://ncidockerhub.nci.nih.gov

    #build files
    - name: build stage for files microservice
      include_role:
        name: bento.common.build_files
      vars:
        ansible_python_interpreter: /usr/bin/python3
        workspace: "{{ lookup('env','WORKSPACE') }}"
        build_number: "{{ lookup('env','BUILD_NUMBER') }}"
        project_name: "{{ project_name }}"
        image_version: "{{ lookup('env','FILES_VERSION') }}"
        #container_name: "files"
        container_name: "filedownloader"
        container_build_path: "{{ workspace }}/{{ project_name }}-files"
        dockerfile_path: "{{ workspace }}/playbooks/docker/dockerfiles/files-microservice-dockerfile"
        ###################################################################################
        #container_registry_url: "{{ ecr_repo }}"
        container_registry_url: "ncidockerhub.nci.nih.gov/icdc"
        ###################################################################################