- name: build frontend microservice
  hosts: all
  connection: local
  gather_facts: no
  #become: yes

  tasks:
    #install collections
    - name: install collections
      command: ansible-galaxy collection install {{ item }}
      loop:
        - community.docker:<=3.3.2
        #- git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,main
        - git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,icdc

    #docker login
    - name: docker login
      include_role:
        name: bento.common.ecr_login
      vars:
        region: us-east-1

    - name: log into ncidockerhub
      docker_login:
        username: "{{ lookup('amazon.aws.aws_secret', 'cbiit/docker.docker_user', nested=true, region='us-east-1') }}"
        password: "{{ lookup('amazon.aws.aws_secret', 'cbiit/docker.docker_password', nested=true, region='us-east-1') }}"
        registry: https://ncidockerhub.nci.nih.gov

    #frontend build
    - name: build frontend
      include_role:
        name: bento.common.build_frontend
      vars:
        ansible_python_interpreter: /usr/bin/python3
        workspace: "{{ lookup('env','WORKSPACE') }}"
        build_number: "{{ lookup('env','BUILD_NUMBER') }}"
        project_name: "{{ project_name }}"
        image_version: "{{ lookup('env','FE_VERSION') }}"
        container_name: "frontend"
        container_build_path: "{{ workspace }}/{{ project_name }}-frontend"
        dockerfile_path: "{{ workspace }}/playbooks/docker/dockerfiles/frontend-icdc-dockerfile"
        ###################################################################################
        #container_registry_url: "{{ ecr_repo }}"
        container_registry_url: "ncidockerhub.nci.nih.gov/icdc"
        ###################################################################################