- name: deploy frontend microservice
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    #install collections
    - name: install aws collection
      shell: "ansible-galaxy collection install {{ item | quote }} --force"
      loop:
        #- community.docker:<=3.4.3
        #- amazon.aws:<=5.4.0
        #- community.aws:<=3.2.0
        #- git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,main
        - git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,icdc

    #docker login
    - name: docker login
      include_role:
        name: bento.common.ecr_login
      vars:
        region: us-east-1

    - name: Get the current caller identity information
      aws_caller_info:
      register: caller_info

    - name: set account number
      set_fact:
        account: "{{ caller_info.account }}"
#    - name: log into ncidockerhub
#      community.docker.docker_login:
#        username: "{{ lookup('amazon.aws.aws_secret', 'cbiit/docker.username', nested=true, region='us-east-1') }}"
#        password: "{{ lookup('amazon.aws.aws_secret', 'cbiit/docker.password', nested=true, region='us-east-1') }}"
#        registry: https://ncidockerhub.nci.nih.gov

    #deploy frontend
    - name: deploy stage for frontend microservice
      include_role:
        name: bento.common.ecs
      vars:
        ansible_python_interpreter: /usr/bin/python3
        project_name: "{{project_name}}"
        region: us-east-1
        container_name: "frontend"
        service_name: "{{ project_name }}-{{ tier }}-frontend"
        program: crdc
        frontend_version: "{{ lookup('env','FE_VERSION') }}"
        backend_version: "{{ lookup('env','BE_VERSION') }}"
        image_version: "{{ frontend_version }}"
        tier: "{{ tier }}"
        execution_role: "{% if iam_prefix is defined and iam_prefix != '' %}{{ iam_prefix }}-{{ project_name }}-{{ tier }}-ecs-task-execution-role{% else %}{{ project_name }}-{{ tier }}-task-execution-role{% endif %}"
        task_role: "{% if iam_prefix is defined and iam_prefix != '' %}{{ iam_prefix }}-{{ project_name }}-{{ tier }}-ecs-task-role{% else %}{{ project_name }}-{{ tier }}-task-role{% endif %}"
        ecs_cluster_name: "{{ project_name }}-{{ tier }}-ecs"
        sumo_collector_endpoint: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project_name }}/{{ tier }}.sumo_collector_endpoint', nested=true, region='us-east-1' ) }}"
        sumo_collector_token: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project_name }}/{{ tier }}.sumo_collector_token_frontend', nested=true, region='us-east-1' ) }}"
        container_port: 80
        container_memory: "512"
        container_cpu: "256"
        ###################################################################################
        container_image_url: "{{ ecr_repo }}/{{program}}-{{ project_name }}-{{ container_name }}"
        #container_image_url: "ncidockerhub.nci.nih.gov/icdc/{{ project_name }}-{{ container_name }}"
        #credentialsParameter: "arn:aws:secretsmanager:{{ region }}:{{ account }}:secret:cbiit/docker"
        ###################################################################################
        backend_google_analytics_id: "UA-154442677-1"
        newrelic_license_key: "{{ lookup('amazon.aws.aws_secret', 'monitoring/newrelic.api_key', nested=true, region='us-east-1' ) }}"
        ##System Info page
        react_app_file_service_version: "{% if tier == 'prod' %}https://{{ subdomain }}.{{ domain_name }}/api/files/version{% else %}https://{{ subdomain }}-{{ tier }}.{{ domain_name }}/api/files/version{% endif %}"
        react_app_interop_service_version: "{% if tier == 'prod' %}https://{{ subdomain }}.{{ domain_name }}/api/interoperation/version{% else %}https://{{ subdomain }}-{{ tier }}.{{ domain_name }}/api/interoperation/version{% endif %}"
        react_app_backend_version: "{% if tier == 'prod' %}https://{{ subdomain }}.{{ domain_name }}/version{% else %}https://{{ subdomain }}-{{ tier }}.{{ domain_name }}/version{% endif %}"
        #react_app_interop_service_version: "https://{{subdomain}}-{{tier}}.{{domain_name}}/api/interoperation/version"
        #react_app_backend_version: "https://{{subdomain}}-{{tier}}.{{domain_name}}/version"
        ## Readme Content ##
        react_app_readme_data:
          dev: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/dev/My_Files_Cart_Page_README.md"
          dev2: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/dev/My_Files_Cart_Page_README.md"
          qa: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/qa/My_Files_Cart_Page_README.md"
          qa2: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/qa/My_Files_Cart_Page_README.md"
          stage: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/stage/My_Files_Cart_Page_README.md"
          prod: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/prod/My_Files_Cart_Page_README.md"
        ## Static Content ##
        react_app_landing_data:
          dev: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/develop/landingView.yaml"
          dev2: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/develop/landingView.yaml"
          qa: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/qa/landingView.yaml"
          qa2: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/qa/landingView.yaml"
          stage: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/stage/landingView.yaml"
          prod: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/production/landingView.yaml"

        react_app_news_data:
          dev: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/develop/newsView.yaml"
          dev2: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/develop/newsView.yaml"
          qa: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/qa/newsView.yaml"
          qa2: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/qa/newsView.yaml"
          stage: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/stage/newsView.yaml"
          prod: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/production/newsView.yaml"

        react_app_about_data:
          dev: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/develop/aboutPagesContent.yaml"
          dev2: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/develop/aboutPagesContent.yaml"
          qa: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/qa/aboutPagesContent.yaml"
          qa2: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/qa/aboutPagesContent.yaml"
          stage: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/stage/aboutPagesContent.yaml"
          prod: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/production/aboutPagesContent.yaml"

        ## readme data ##
        react_app_readme_url:
          dev: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/dev/Data_Model_Navigator_README.md"
          dev2: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/dev/Data_Model_Navigator_README.md"
          qa: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/qa/Data_Model_Navigator_README.md"
          qa2: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/qa/Data_Model_Navigator_README.md"
          stage: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/stage/Data_Model_Navigator_README.md"
          prod: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/prod/Data_Model_Navigator_README.md"

        ## privacy policy ##
        react_app_footer_privacy_policy:
          dev: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/dev/Privacy_Policy.md"
          dev2: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/dev/Privacy_Policy.md"
          qa: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/qa/Privacy_Policy.md"
          qa2: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/qa/Privacy_Policy.md"
          stage: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/stage/Privacy_Policy.md"
          prod: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/prod/Privacy_Policy.md"

        container_env:
          # API URLs
          - name: REACT_APP_BACKEND_API
            value: "{% if tier == 'prod'  and project_name == 'bento' %}https://{{domain_name}}/v1/graphql/{% elif tier == 'prod' %}https://{{subdomain}}.{{domain_name}}/v1/graphql/{% else %}https://{{subdomain}}-{{tier}}.{{domain_name}}/v1/graphql/{% endif %}"
            #value: "https://caninecommons-test.cancer.gov/v1/graphql/"
          - name: REACT_APP_BACKEND_GETUSERINFO_API
            value: "https://{{subdomain}}.{{domain_name}}/fence/login/"
          - name: REACT_APP_FILE_SERVICE_API
            value: "{% if tier == 'prod' %}https://{{subdomain}}.{{domain_name}}/api/files/{% else %}https://{{subdomain}}-{{tier}}.{{domain_name}}/api/files/{% endif %}"
            #value: "https://caninecommons-test.cancer.gov/api/files/"
          - name: REACT_APP_INTEROP_SERVICE_URL
            value: "{% if tier == 'prod' %}https://{{subdomain}}.{{domain_name}}/api/interoperation/graphql{% else %}https://{{subdomain}}-{{tier}}.{{domain_name}}/api/interoperation/graphql{% endif %}"
            #value: "https://caninecommons-test.cancer.gov/api/interoperation/graphql"
          - name: REACT_APP_LOGIN_URL
            value: "https://nci-crdc-staging.datacommons.io/user/oauth2/authorize?client_id=HADoUzN9BWzbzwxdu0soRvRHSnegiWaoShVhB09O&response_type=code&redirect_uri=https://clinical-{{ tier }}.datacommons.cancer.gov/login&scope=openid%20user%20data"

          #- name: REACT_APP_USER_LOGOUT_URL
          #  value: "{{ backend_fence_logout }}"
          # Static Content
          - name: REACT_APP_ABOUT_CONTENT_URL
            value: "{{ react_app_about_data[tier] }}"
          - name: REACT_APP_LANDING_DATA
            value: "{{ react_app_landing_data[tier] }}"
          - name: REACT_APP_NEWS_DATA
            value: "{{ react_app_news_data[tier] }}"
          - name: REACT_APP_DMN_README
            value: "{{ react_app_readme_url[tier] }}"
          - name: REACT_APP_FOOTER_PRIVACY_POLICY
            value: "{{ react_app_footer_privacy_policy[tier] }}"
          # Data Model
          - name: REACT_APP_DATA_MODEL
            value: "{% if tier == 'prod' %}https://raw.githubusercontent.com/CBIIT/icdc-model-tool/{{data_model_branch | default('master')}}/model-desc/icdc-model.yml{% else %}https://raw.githubusercontent.com/CBIIT/icdc-model-tool/{{data_model_branch | default('develop')}}/model-desc/icdc-model.yml{% endif %}"
          - name: REACT_APP_DATA_MODEL_PROPS
            value: "{% if tier == 'prod' %}https://raw.githubusercontent.com/CBIIT/icdc-model-tool/{{data_model_branch | default('master')}}/model-desc/icdc-model-props.yml{% else %}https://raw.githubusercontent.com/CBIIT/icdc-model-tool/{{data_model_branch | default('develop')}}/model-desc/icdc-model-props.yml{% endif %}"
          # New Relic
          - name: NEW_RELIC_LICENSE_KEY
            value: "{{ newrelic_license_key }}"
          - name: NEW_RELIC_APP_NAME
            value: "{{ project_name }}-{{ tier }}-{{ container_name }}"
          - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
            value: "true"
          - name: NEW_RELIC_HOST
            value: "gov-collector.newrelic.com"
          - name: NEW_RELIC_NO_CONFIG_FILE
            value: "true"
          - name: NEW_RELIC_LABELS
            value: "Project:{{ project_name }};Environment:{{ tier }}"
          # Versions
          - name: REACT_APP_BE_VERSION
            value: "{{ backend_version }}"
          - name: REACT_APP_FE_VERSION
            value: "{{ frontend_version }}"
          # Analytics
          - name: REACT_APP_GA_TRACKING_ID
            value: "{{ backend_google_analytics_id }}"
          # Readme Content
          - name: REACT_APP_FILE_CENTRIC_CART_README
            value: "{{ react_app_readme_data[tier] }}"
          # System Info page
          - name: REACT_APP_FILE_SERVICE_VERSION
            value: "{{ react_app_file_service_version }}"
          - name: REACT_APP_INTEROP_SERVICE_VERSION
            value: "{{ react_app_interop_service_version }}"
          - name: REACT_APP_BACKEND_VERSION
            value: "{{ react_app_backend_version }}"
