
---
- name: restore data dump 
  hosts: all
  gather_facts: yes
  become: yes
  remote_user: commonsdocker
  tasks:
    - name: restore neo4j data dump
      include_role:
        name: neo4j_dump
        tasks_from: data-restore