- name: load data
  #hosts: all
  hosts: loader
  connection: local
  gather_facts: no

  tasks:
    #install collections
    - name: install aws collection
      shell: "ansible-galaxy collection install {{ item | quote }}"
      loop:
       # -  amazon.aws:<=5.4.0
       # -  community.aws:<=3.2.0
       # -  community.docker:<=2.7.1
        #- git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,v1.19
        - git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,dataloader_test
    
    #run data loader
    - name: data loader stage
      include_role:
        name: bento.common.data_loader
      vars:
        ansible_python_interpreter: /usr/bin/python3
        platform: aws
        region: us-east-1
        project: "icdc"
        #tier: "{{ lookup('env','TIER') }}"
        workspace: "{{ lookup('env','WORKSPACE') }}"
        #model_file1: "{{ workspace }}/{{ project }}-model/model-desc/{{ model_file_1 }}"
        #model_file2: "{{ workspace }}/{{ project }}-model/model-desc/{{ model_file_2 }}"
        model_file1: "{{ workspace }}/{{ project }}-model/model-desc/icdc-model.yml"
        model_file2: "{{ workspace }}/{{ project }}-model/model-desc/icdc-model-props.yml"
        #property_file: "config/{{property_File}}"
        property_file: "config/props-icdc-pmvp.yml"
        neo4j_user: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project }}/{{ tier }}.neo4j_user', nested=true, region='us-east-1' ) }}"
        #neo4j_ip: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project }}/{{ tier }}.neo4j_ip', nested=true, region='us-east-1' ) }}"
        neo4j_ip: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project }}/{{ tier }}.neo4j_old', nested=true, region='us-east-1' ) }}"
        neo4j_password: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project }}/{{ tier }}.neo4j_password', nested=true, region='us-east-1' ) }}"
        #s3_folder: "{{ lookup('env','S3_FOLDER') }}"
        #wipe_db: "{{ lookup('env','WIPE_DB') }}"
        #cheat_mode: "{{ lookup('env','CHEAT_MODE') }}"
        #split_transactions: "{{ lookup('env','SPLIT_TRANSACTIONS') }}"
        #data_bucket: "{{ lookup('env','DATA_BUCKET') }}"
        loading_mode: "upsert"
        #Elasticsearch
        #es_host: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project }}/{{ tier }}.es_host', nested=true, region='us-east-1' ) }}"
