- name: build backend microservice
  hosts: all
  gather_facts: no
  connection: local
  become: yes

  tasks:
    - debug: var=ansible_python_version
    #install collections
    - name: install aws collection
      command: ansible-galaxy collection install {{item}}
      loop:
        - community.docker
        - amazon.aws
        - community.aws:<=3.2.0
        - git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,main

    #docker login
    - name: docker login
      include_role:
        name: bento.common.ecr_login
      vars:
        region: us-east-1
    - debug:
        msg: "Here is the ECR repo {{ecr_repo}}"
    #build backend
    - name: build {{project_name}} backend
      include_role:
        name: bento.common.build_backend
      vars:
        ansible_python_interpreter: /usr/bin/python3
        workspace: "{{ lookup('env','WORKSPACE') }}"
        build_number: "{{ lookup('env','BUILD_NUMBER')}}"
        project_name: "{{ lookup('env','PROJECT_NAME') }}"
        project: "{{ project_name }}"
        image_version: "{{ lookup('env','BE_VERSION') }}"
        tier: "{{ tier }}"
        bento_api_version: "{{ image_version }}"
        container_name: "backend"
        schema_file: "{%if project_name == 'bento' %}{{ project_name }}-extended.graphql{% else %}{{ project_name }}.graphql{% endif %}"
        es_schema_file: "{{ project_name }}-private-es-schema.graphql"
        public_schema_file: "{%if project_name == 'bento' %}{{ project_name }}-extended-public.graphql{% else %}{{ project_name }}-public.graphql{% endif %}"
        public_es_schema_file: "{{ project_name }}-public-es-schema.graphql"
        es_host: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project_name }}/{{ tier }}.es_host', nested=true, region='us-east-1' ) }}"
        test_queries_file: "not_needed.txt"
        dockerfile_path: "{{workspace}}/icdc-devops/docker/dockerfiles/backend-microservice-dockerfile"
        container_image: "{{ ecr_repo }}/{{ project_name }}-{{ container_name }}:{{ image_version }}s"
        container_registry_url: "{{ ecr_repo }}"
        auth_enabled: "true"