- name: deploy frontend microservice
  hosts: all
  connection: local
  gather_facts: no
  become: yes

  tasks:
    #install collections
    - name: install aws collection
      command: ansible-galaxy collection install {{item}}
      loop:
        - community.docker
        - amazon.aws
        - community.aws:<=3.2.0
        - git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,main

    #docker login
    - name: docker login
      include_role:
        name: bento.common.ecr_login
      vars:
        region: us-east-1

    #deploy frontend
    - name: deploy stage for frontend microservice
      include_role:
        name: bento.common.ecs
      vars:
        ansible_python_interpreter: /usr/bin/python3
        project_name: "{{project_name}}"
        region: us-east-1
        container_name: "frontend"
        frontend_version: "{{ lookup('env','FE_VERSION') }}"
        backend_version: "{{ lookup('env','BE_VERSION') }}"
        image_version: "{{ frontend_version }}"
        tier: "{{ tier }}"
        execution_role: "{% if iam_prefix is defined and iam_prefix != '' %}{{ iam_prefix }}-{{ project_name }}-{{ tier }}-ecs-task-execution-role{% else %}{{ project_name }}-{{ tier }}-task-execution-role{% endif %}"
        task_role: "{% if iam_prefix is defined and iam_prefix != '' %}{{ iam_prefix }}-{{ project_name }}-{{ tier }}-ecs-task-role{% else %}{{ project_name }}-{{ tier }}-task-role{% endif %}"
        ecs_cluster_name: "{{ project_name }}-{{ tier }}-ecs"
        sumo_collector_endpoint: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project_name }}/{{ tier }}.sumo_collector_endpoint', nested=true, region='us-east-1' ) }}"
        sumo_collector_token: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project_name }}/{{ tier }}.sumo_collector_token_frontend', nested=true, region='us-east-1' ) }}"
        container_port: 80
        container_memory: "512"
        container_cpu: "256"
        container_image_url: "{{ ecr_repo }}/{{ project_name }}-{{ container_name }}"
        about_content_url: "https://raw.githubusercontent.com/CBIIT/bento-frontend/master/src/content/{{ tier }}/aboutPagesContent.yaml"
        newrelic_license_key: "{{ lookup('amazon.aws.aws_secret', 'monitoring/newrelic.api_key', nested=true, region='us-east-1' ) }}"
        app_google_client_id: "{{ lookup('amazon.aws.aws_secret', 'auth/provider/google.idp_client_id', nested=true, region='us-east-1' ) }}"
        container_env:
          - name: REACT_APP_BACKEND_API
            value: "{% if tier == 'prod'  and project_name == 'bento' %}https://{{domain_name}}/v1/graphql/{% elif tier == 'prod' %}https://{{subdomain}}.{{domain_name}}/v1/graphql/{% else %}https://{{subdomain}}-{{tier}}.{{domain_name}}/v1/graphql/{% endif %}"
          - name: REACT_APP_FILE_SERVICE_API
            value: "{% if tier == 'prod'  and project_name == 'bento' %}https://{{domain_name}}/api/files/{% elif tier == 'prod' %}https://{{subdomain}}.{{domain_name}}/api/files/{% else %}https://{{subdomain}}-{{tier}}.{{domain_name}}/api/files//{% endif %}"
          - name: REACT_APP_BE_VERSION
            value: "{{ backend_version }}"
          - name: REACT_APP_FE_VERSION
            value: "{{ frontend_version }}"
          - name: REACT_APP_ABOUT_CONTENT_URL
            value: "{{ about_content_url }}"
          - name: REACT_APP_AUTH_SERVICE_API
            value: "{% if tier == 'prod'  and project_name == 'bento' %}https://{{domain_name}}/api/auth/{% elif tier == 'prod' %}https://{{subdomain}}.{{domain_name}}/api/auth/{% else %}https://{{subdomain}}-{{tier}}.{{domain_name}}/api/auth/{% endif %}"
          - name: REACT_APP_USER_SERVICE_API
            value: "{% if tier == 'prod'  and project_name == 'bento' %}https://{{domain_name}}/api/users/{% elif tier == 'prod' %}https://{{subdomain}}.{{domain_name}}/api/users/{% else %}https://{{subdomain}}-{{tier}}.{{domain_name}}/api/users/{% endif %}"
          - name: REACT_APP_NIH_CLIENT_ID
            value: "{{ lookup('amazon.aws.aws_secret', 'auth/provider/nih.nih_client_id', nested=true, region='us-east-1' ) }}"
          - name: REACT_APP_NIH_AUTH_URL
            value: "{{ lookup('amazon.aws.aws_secret', 'auth/provider/nih.nih_client_url', nested=true, region='us-east-1' ) }}"
          - name: NEW_RELIC_LICENSE_KEY
            value: "{{ newrelic_license_key }}"
          - name: NEW_RELIC_APP_NAME
            value: "{{ project_name }}-{{ tier }}-{{ container_name }}"
          - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
            value: "true"
          - name: NEW_RELIC_HOST
            value: "gov-collector.newrelic.com"
          - name: NEW_RELIC_NO_CONFIG_FILE
            value: "true"
          - name: NEW_RELIC_LABELS
            value: "Project:{{ project_name }};Environment:{{ tier }}"
          - name: REACT_APP_GOOGLE_CLIENT_ID
            value: "{{ app_google_client_id }}"
          - name: REACT_APP_BACKEND_PUBLIC_API
            value: "{% if tier == 'prod'  and project_name == 'bento' %}https://{{domain_name}}/v1/public-graphql/{% elif tier == 'prod' %}https://{{subdomain}}.{{domain_name}}/v1/public-graphql/{% else %}https://{{subdomain}}-{{tier}}.{{domain_name}}/v1/public-graphql/{% endif %}"
          - name: REACT_APP_AUTH_API
            value: "{% if tier == 'prod'  and project_name == 'bento' %}https://{{domain_name}}{% elif tier == 'prod' %}https://{{subdomain}}.{{domain_name}}{% else %}https://{{subdomain}}-{{tier}}.{{domain_name}}{% endif %}"
